In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import datasets

In [ ]:
from keras.datasets import imdb
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

17473536/17464789 [==============================] - 0s 0us/step


The argument num_words=10000 means you’ll only keep the top 10,000 most fre-
quently occurring words in the training data. Rare words will be discarded. This allows
you to work with vector data of manageable size.

In [ ]:
train_data[0]

he variables train_data and test_data are lists of reviews; each review is a list of
word indices (encoding a sequence of words). 

In [ ]:
train_labels[0]

1

train_labels and test_labels are
lists of 0s and 1s, where 0 stands for negative and 1 stands for positive:

In [ ]:
max([max(sequence) for sequence in train_data])

9999

In [ ]:
import numpy as np
def vectorize_sequences(sequences, dimension=10000):   #Creates an all-zero matrix of shape (len(sequences), dimension)
  results = np.zeros((len(sequences), dimension))
  for i, sequence in enumerate(sequences):
    results[i, sequence] = 1. #Sets specific indices of results[i] to 1s
  return results
x_train = vectorize_sequences(train_data) #vectorized training data
x_test = vectorize_sequences(test_data) #Vectorized test data
print(x_train)
print(x_test)

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]
[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]


In [ ]:
x_train[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [ ]:
y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')

In [ ]:
y_train

array([1., 0., 0., ..., 0., 1., 0.], dtype=float32)

In [ ]:
y_test

array([0., 1., 1., ..., 0., 0., 0.], dtype=float32)

In [ ]:
from keras import models
from keras import layers
model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
x_val = x_train[:10000] 
partial_x_train = x_train[10000:]
y_val = y_train[:10000] 
partial_y_train = y_train[10000:]

In [ ]:
import tensorflow as tf
call_backs = [tf.keras.callbacks.TensorBoard(log_dir='./logs')]

In [ ]:
history = model.fit(partial_x_train, partial_y_train, epochs=20, batch_size=512, validation_data=(x_val, y_val),callbacks = call_backs)

Epoch 1/20
30/30 [==============================] - 1s 30ms/step - loss: 0.5427 - accuracy: 0.7655 - val_loss: 0.3926 - val_accuracy: 0.8562
Epoch 2/20
30/30 [==============================] - 0s 16ms/step - loss: 0.2913 - accuracy: 0.9019 - val_loss: 0.2916 - val_accuracy: 0.8850
Epoch 3/20
30/30 [==============================] - 1s 17ms/step - loss: 0.1951 - accuracy: 0.9351 - val_loss: 0.2814 - val_accuracy: 0.8877
Epoch 4/20
30/30 [==============================] - 1s 18ms/step - loss: 0.1450 - accuracy: 0.9548 - val_loss: 0.2864 - val_accuracy: 0.8856
Epoch 5/20
30/30 [==============================] - 1s 18ms/step - loss: 0.1107 - accuracy: 0.9683 - val_loss: 0.2996 - val_accuracy: 0.8828
Epoch 6/20
30/30 [==============================] - 0s 16ms/step - loss: 0.0851 - accuracy: 0.9785 - val_loss: 0.3242 - val_accuracy: 0.8819
Epoch 7/20
30/30 [==============================] - 1s 28ms/step - loss: 0.0648 - accuracy: 0.9869 - val_loss: 0.3487 - val_accuracy: 0.8802
Epoch 8/20
30

In [ ]:
test_loss, test_acc = model.evaluate(x_test, y_test)

782/782 [==============================] - 2s 2ms/step - loss: 0.6986 - accuracy: 0.8550


In [ ]:
%load_ext tensorboard
import tensorflow as tf
import datetime

In [ ]:
%tensorboard --logdir logs/fit

<IPython.core.display.Javascript object>

In [ ]:
from tensorboard import notebook
notebook.list() # View open TensorBoard

Known TensorBoard instances:
  - port 6006: logdir logs/fit (started 0:00:00 ago; pid 235)


In [ ]:
# Control TensorBoard display. If no port is provided, 
# the most recently launched TensorBoard is used
notebook.display(port=6006, height=1000)

In [ ]:
!tensorboard dev upload \
  --logdir logs \
  --name "Keras_IMDB" \
  --description "TB" \
  --one_shot

2022-08-22 13:25:32.492193: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

***** TensorBoard Uploader *****

This will upload your TensorBoard logs to https://tensorboard.dev/ from
the following directory:

logs

This TensorBoard will be visible to everyone. Do not upload sensitive
data.

Your use of this service is subject to Google's Terms of Service
<https://policies.google.com/terms> and Privacy Policy
<https://policies.google.com/privacy>, and TensorBoard.dev's Terms of Service
<https://tensorboard.dev/policy/terms/>.

This notice will not be shown again while you are logged into the uploader.
To log out, run `tensorboard dev auth revoke`.

Continue? (yes/NO) yes

Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=373649185512-8v619h5kft38l4456nm2dj4ubeqsrvh6.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%