

Example data:

An experiemental drug was tested on individuals from ages 13 to 100.
The trial had 2100 participants. Half were under 65 years old, half were  over 65 years old.
95% of patientes 65 or older experienced side effects.
95% of patients under 65 experienced no side effects.

 Neural Network Predictions with TensorFlow's Keras API

In [1]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

In [2]:
train_labels = []
train_samples = []

In [3]:
for i in range(50):
  # The 5% of younger individuals who did experience side effects
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(1)

  # The 5% of older individuals who did not experience side effects
  random_older = randint(65,100)
  train_samples.append(random_older)
  train_labels.append(0)

for i in range(1000):
  # The 95% of younger individuals who did not experience side effects
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(0)

  # The 95% of older individuals who did experience side effects
  random_older = randint(65,100)
  train_samples.append(random_older)
  train_labels.append(1)

In [4]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels,train_samples = shuffle(train_labels,train_samples)

In [6]:
scaler = MinMaxScaler(feature_range = (0,1))
sc_trained_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [7]:
sc_trained_samples = np.array(sc_trained_samples)
sc_trained_samples

array([[0.62068966],
       [0.88505747],
       [0.57471264],
       ...,
       [0.96551724],
       [0.56321839],
       [0.06896552]])

In [9]:
!pip install keras 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [10]:
import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense
from keras.optimizers import adam_v2
from keras.metrics import categorical_crossentropy
from keras import optimizers
from keras import metrics

In [38]:
model = Sequential([
                    Dense(units = 160,input_shape = (1,),activation = 'relu'),
                    Dense(units = 320,activation = 'relu'),
                    Dense(units = 2,activation = 'softmax')
])

Predict

In [39]:
prediction = model.predict(x = sc_trained_samples,batch_size = 10,verbose = 0)

In [40]:
for i in prediction:
  print(i)

[0.47879562 0.5212044 ]
[0.4697828 0.5302172]
[0.48036462 0.5196354 ]
[0.48154166 0.51845837]
[0.47448304 0.5255169 ]
[0.4905713  0.50942874]
[0.4846813 0.5153187]
[0.47330755 0.52669245]
[0.4686086  0.53139144]
[0.48114926 0.51885074]
[0.47134903 0.528651  ]
[0.4776191 0.5223809]
[0.49607098 0.503929  ]
[0.49607098 0.503929  ]
[0.49646387 0.50353616]
[0.49253523 0.5074647 ]
[0.49489236 0.50510764]
[0.4662611  0.53373885]
[0.49803543 0.5019645 ]
[0.47840342 0.5215966 ]
[0.47291577 0.52708423]
[0.48742953 0.51257044]
[0.4890003 0.5109997]
[0.47526687 0.5247331 ]
[0.4701743 0.5298257]
[0.49096406 0.50903594]
[0.4984284  0.50157166]
[0.4776191 0.5223809]
[0.47056586 0.52943414]
[0.47330755 0.52669245]
[0.49410662 0.50589335]
[0.48271886 0.5172811 ]
[0.48075697 0.51924306]
[0.47997236 0.5200277 ]
[0.4846813 0.5153187]
[0.4988213  0.50117874]
[0.48350376 0.5164962 ]
[0.47330755 0.52669245]
[0.49371377 0.5062862 ]
[0.47997236 0.5200277 ]
[0.47174063 0.52825934]
[0.46743467 0.53256536]
[0.485

In [41]:
rounded_prediction = np.argmax(prediction,axis = 1)
rounded_prediction

array([1, 1, 1, ..., 1, 1, 1])

In [42]:
for i in rounded_prediction:
  print(i)

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


Confusion Matrix

In [43]:
%matplotlib inline
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt

In [44]:
cm = confusion_matrix(y_true = train_labels,y_pred = rounded_prediction)

In [45]:
cm

array([[  24, 1026],
       [   1, 1049]])