

Example data:

An experiemental drug was tested on individuals from ages 13 to 100. The trial had 2100 participants. Half were under 65 years old, half were over 65 years old. 95% of patientes 65 or older experienced side effects. 95% of patients under 65 experienced no side effects.


In [3]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

In [4]:
train_labels = []
train_samples = []

In [5]:
for i in range(50):
  # The 5% of younger individuals who did experience side effects
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(1)

  # The 5% of older individuals who did not experience side effects
  random_older = randint(65,100)
  train_samples.append(random_older)
  train_labels.append(0)

for i in range(1000):
  # The 95% of younger individuals who did not experience side effects
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(0)

  # The 95% of older individuals who did experience side effects
  random_older = randint(65,100)
  train_samples.append(random_older)
  train_labels.append(1)

In [6]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels,train_samples = shuffle(train_labels,train_samples)

In [7]:
train_labels

array([1, 0, 0, ..., 1, 1, 1])

In [8]:
train_samples

array([88, 45, 88, ..., 86, 77, 90])

In [ ]:
train_labels,train_samples

(array([0, 1, 0, ..., 0, 0, 0]), array([28, 71, 82, ..., 13, 18, 50]))

In [ ]:
shuffle(train_labels,train_samples)

[array([0, 0, 0, ..., 0, 1, 1]), array([55, 37, 62, ..., 29, 97, 95])]

In [9]:
scaler = MinMaxScaler(feature_range = (0,1))
sc_trained_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [10]:
for i in sc_trained_samples:
  print(i)

[0.86206897]
[0.36781609]
[0.86206897]
[0.06896552]
[0.67816092]
[0.31034483]
[0.59770115]
[0.87356322]
[0.14942529]
[1.]
[0.93103448]
[0.95402299]
[0.64367816]
[0.70114943]
[0.35632184]
[0.16091954]
[0.93103448]
[0.31034483]
[0.85057471]
[0.86206897]
[0.88505747]
[0.64367816]
[0.06896552]
[0.29885057]
[0.71264368]
[0.7816092]
[0.68965517]
[0.45977011]
[0.32183908]
[0.42528736]
[0.89655172]
[0.94252874]
[0.48275862]
[0.14942529]
[0.94252874]
[0.57471264]
[0.]
[0.88505747]
[0.]
[0.90804598]
[0.90804598]
[0.72413793]
[0.4137931]
[0.01149425]
[0.91954023]
[0.65517241]
[0.74712644]
[0.93103448]
[0.94252874]
[0.04597701]
[0.08045977]
[0.59770115]
[0.66666667]
[0.22988506]
[0.52873563]
[0.33333333]
[0.90804598]
[0.42528736]
[0.06896552]
[0.86206897]
[0.43678161]
[0.64367816]
[0.98850575]
[0.72413793]
[0.98850575]
[0.98850575]
[0.7816092]
[0.54022989]
[0.94252874]
[0.89655172]
[0.31034483]
[0.28735632]
[0.05747126]
[0.94252874]
[0.82758621]
[0.88505747]
[0.13793103]
[0.4137931]
[0.4137931]
[0

In [12]:
sc_trained_samples = np.array(sc_trained_samples)
sc_trained_samples

array([[0.86206897],
       [0.36781609],
       [0.86206897],
       ...,
       [0.83908046],
       [0.73563218],
       [0.88505747]])

In [13]:
!pip install keras 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [23]:
import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense
from keras.optimizers import adam
from keras.metrics import categorical_crossentropy
from keras import optimizers
from keras import metrics

ImportError: ignored

In [30]:
model = Sequential([
                    Dense(units = 160,input_shape = (1,),activation = 'relu'),
                    Dense(units = 320,activation = 'relu'),
                    Dense(units = 2,activation = 'softmax')
])

In [31]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 160)               320       
                                                                 
 dense_7 (Dense)             (None, 320)               51520     
                                                                 
 dense_8 (Dense)             (None, 2)                 642       
                                                                 
Total params: 52,482
Trainable params: 52,482
Non-trainable params: 0
_________________________________________________________________


In [32]:
model.loss = 'sparse_categorical_crossentropy'

In [33]:
#model.compile(optimizer=adam_v2, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.compile(loss='sparse_categorical_crossentropy')

In [34]:
model.fit(sc_trained_samples, train_labels, batch_size=10, epochs=20, shuffle=True, verbose=2)

Epoch 1/20
210/210 - 1s - loss: 0.3390 - 751ms/epoch - 4ms/step
Epoch 2/20
210/210 - 0s - loss: 0.2573 - 285ms/epoch - 1ms/step
Epoch 3/20
210/210 - 0s - loss: 0.2499 - 293ms/epoch - 1ms/step
Epoch 4/20
210/210 - 0s - loss: 0.2435 - 299ms/epoch - 1ms/step
Epoch 5/20
210/210 - 0s - loss: 0.2372 - 286ms/epoch - 1ms/step
Epoch 6/20
210/210 - 0s - loss: 0.2391 - 300ms/epoch - 1ms/step
Epoch 7/20
210/210 - 0s - loss: 0.2353 - 287ms/epoch - 1ms/step
Epoch 8/20
210/210 - 0s - loss: 0.2256 - 295ms/epoch - 1ms/step
Epoch 9/20
210/210 - 0s - loss: 0.2219 - 286ms/epoch - 1ms/step
Epoch 10/20
210/210 - 0s - loss: 0.2213 - 299ms/epoch - 1ms/step
Epoch 11/20
210/210 - 0s - loss: 0.2204 - 283ms/epoch - 1ms/step
Epoch 12/20
210/210 - 0s - loss: 0.2189 - 297ms/epoch - 1ms/step
Epoch 13/20
210/210 - 0s - loss: 0.2117 - 278ms/epoch - 1ms/step
Epoch 14/20
210/210 - 0s - loss: 0.2130 - 279ms/epoch - 1ms/step
Epoch 15/20
210/210 - 0s - loss: 0.2179 - 293ms/epoch - 1ms/step
Epoch 16/20
210/210 - 0s - loss: 0

In [20]:
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential([
    Dense(32, input_shape=(10,), activation='relu'),
    Dense(2, activation='softmax'),
])


In [21]:
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential([
    Dense(5, input_shape=(3,), activation='relu'),
    Dense(2, activation='softmax'),
])

In [28]:
import numpy as np
import scipy
import imageio
from scipy import ndimage
import matplotlib.pyplot as plt
%matplotlib inline

img = np.expand_dims(imageio.imread('NN.PNG'),0)
plt.imshow(img[0])

FileNotFoundError: ignored

In [29]:
model.fit(sc_trained_samples, train_labels, batch_size=10, epochs=20, shuffle=True, verbose=2)


NameError: ignored