Example data:

An experiemental drug was tested on individuals from ages 13 to 100. The trial had 2100 participants. Half were under 65 years old, half were over 65 years old. 95% of patientes 65 or older experienced side effects. 95% of patients under 65 experienced no side effects.



In [ ]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

In [ ]:
train_labels = []
train_samples = []

In [ ]:
for i in range(50):
  # The 5% of younger individuals who did experience side effects
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(1)

  # The 5% of older individuals who did not experience side effects
  random_older = randint(65,100)
  train_samples.append(random_older)
  train_labels.append(0)

for i in range(1000):
  # The 95% of younger individuals who did not experience side effects
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(0)

  # The 95% of older individuals who did experience side effects
  random_older = randint(65,100)
  train_samples.append(random_older)
  train_labels.append(1)

In [ ]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels,train_samples = shuffle(train_labels,train_samples)

In [ ]:
scaler = MinMaxScaler(feature_range = (0,1))
sc_trained_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [ ]:
sc_trained_samples = np.array(sc_trained_samples)
sc_trained_samples

array([[0.54022989],
       [0.93103448],
       [0.31034483],
       ...,
       [0.67816092],
       [0.75862069],
       [0.28735632]])

In [ ]:
!pip install keras 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense
from keras.optimizers import adam_v2
from keras.metrics import categorical_crossentropy
from keras import optimizers
from keras import metrics

In [ ]:
model = Sequential([
                    Dense(units = 16,input_shape = (1,),activation = 'relu'),
                    Dense(units = 32,activation = 'relu'),
                    Dense(units = 2,activation = 'softmax')
])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.loss = 'sparse_categorical_crossentropy'

In [ ]:
#model.compile(optimizer=adam_v2, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam')

In [ ]:
model.fit(sc_trained_samples, train_labels, batch_size=10, epochs=200, shuffle=True, verbose=2)

Epoch 1/200
210/210 - 1s - loss: 0.5550 - 1s/epoch - 6ms/step
Epoch 2/200
210/210 - 0s - loss: 0.3378 - 254ms/epoch - 1ms/step
Epoch 3/200
210/210 - 0s - loss: 0.2648 - 272ms/epoch - 1ms/step
Epoch 4/200
210/210 - 0s - loss: 0.2500 - 268ms/epoch - 1ms/step
Epoch 5/200
210/210 - 0s - loss: 0.2429 - 262ms/epoch - 1ms/step
Epoch 6/200
210/210 - 0s - loss: 0.2395 - 289ms/epoch - 1ms/step
Epoch 7/200
210/210 - 0s - loss: 0.2366 - 258ms/epoch - 1ms/step
Epoch 8/200
210/210 - 0s - loss: 0.2340 - 266ms/epoch - 1ms/step
Epoch 9/200
210/210 - 0s - loss: 0.2330 - 256ms/epoch - 1ms/step
Epoch 10/200
210/210 - 0s - loss: 0.2335 - 257ms/epoch - 1ms/step
Epoch 11/200
210/210 - 0s - loss: 0.2310 - 259ms/epoch - 1ms/step
Epoch 12/200
210/210 - 0s - loss: 0.2314 - 273ms/epoch - 1ms/step
Epoch 13/200
210/210 - 0s - loss: 0.2294 - 266ms/epoch - 1ms/step
Epoch 14/200
210/210 - 0s - loss: 0.2290 - 259ms/epoch - 1ms/step
Epoch 15/200
210/210 - 0s - loss: 0.2269 - 265ms/epoch - 1ms/step
Epoch 16/200
210/210 -

1.model.save()

In [ ]:
import os.path


In [ ]:
if os.path.isfile("model.h5") is False: 
  model.save("model.h5")

In [ ]:
from tensorflow.keras.models import Model, load_model, save_model
new_model = load_model("model.h5")

In [ ]:
new_model

In [ ]:
new_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [ ]:
new_model.get_weights()

[array([[-0.36819646, -0.4172001 , -0.21200284, -0.05569041, -0.22336197,
         -0.23143709,  0.51239145, -0.52779484, -0.49427646, -0.0229556 ,
          0.70642626,  0.32861006,  0.5767585 ,  0.7899178 , -0.573041  ,
          0.65643185]], dtype=float32),
 array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.29650623,  0.        ,  0.        ,  0.        ,
        -0.40761548,  0.20406082, -0.13868164, -0.455474  ,  0.        ,
        -0.3792329 ], dtype=float32),
 array([[ 2.96590596e-01,  1.55656427e-01, -2.60745347e-01,
          6.06419742e-02, -2.87129521e-01,  3.28592092e-01,
          2.52136499e-01,  6.36572540e-02, -2.79710919e-01,
         -3.36222589e-01,  1.37292594e-01,  2.12605596e-02,
          3.05263191e-01, -1.25352144e-01, -1.31993309e-01,
          1.19592100e-01, -3.19579482e-01,  1.09190762e-01,
          3.00973564e-01, -2.02332258e-01, -3.36308569e-01,
         -1.41147688e-01,  2.61187047e-01,  8.26457143e-03,
 

In [ ]:
new_model.optimizer

model.to_json()
if yo only need to save the architecture of the model not the weights and the training configuration you can use the following function to save the architecture only.

In [ ]:
json_model = model.to_json() 

In [ ]:
json_model

'{"class_name": "Sequential", "config": {"name": "sequential", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 1], "dtype": "float32", "sparse": false, "ragged": false, "name": "dense_input"}}, {"class_name": "Dense", "config": {"name": "dense", "trainable": true, "batch_input_shape": [null, 1], "dtype": "float32", "units": 16, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 32, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_r

In [ ]:
from tensorflow.keras.models import model_from_json

In [ ]:
model_arch = model_from_json(json_model) 

In [ ]:
model_arch

In [ ]:
model_arch.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


model.save_weights()
if you only need to save the weights

In [ ]:
import os.path
if os.path.isfile("model.h5") is False: 
  model.save_weights("model.h5")
else:
  print("Saved")

Saved


In [ ]:
model2 = Sequential([
                    Dense(units = 16,input_shape = (1,),activation = 'relu'),
                    Dense(units = 32,activation = 'relu'),
                    Dense(units = 2,activation = 'softmax')
])

In [ ]:
model2.load_weights("model2.h5")

OSError: ignored

In [ ]:
model.get_weights()

[array([[-0.36819646, -0.4172001 , -0.21200284, -0.05569041, -0.22336197,
         -0.23143709,  0.51239145, -0.52779484, -0.49427646, -0.0229556 ,
          0.70642626,  0.32861006,  0.5767585 ,  0.7899178 , -0.573041  ,
          0.65643185]], dtype=float32),
 array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.29650623,  0.        ,  0.        ,  0.        ,
        -0.40761548,  0.20406082, -0.13868164, -0.455474  ,  0.        ,
        -0.3792329 ], dtype=float32),
 array([[ 2.96590596e-01,  1.55656427e-01, -2.60745347e-01,
          6.06419742e-02, -2.87129521e-01,  3.28592092e-01,
          2.52136499e-01,  6.36572540e-02, -2.79710919e-01,
         -3.36222589e-01,  1.37292594e-01,  2.12605596e-02,
          3.05263191e-01, -1.25352144e-01, -1.31993309e-01,
          1.19592100e-01, -3.19579482e-01,  1.09190762e-01,
          3.00973564e-01, -2.02332258e-01, -3.36308569e-01,
         -1.41147688e-01,  2.61187047e-01,  8.26457143e-03,
 