

Example data:

An experiemental drug was tested on individuals from ages 13 to 100. The trial had 2100 participants. Half were under 65 years old, half were over 65 years old. 95% of patientes 65 or older experienced side effects. 95% of patients under 65 experienced no side effects.


In [2]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

In [3]:
train_labels = []
train_samples = []

In [4]:
for i in range(50):
  # The 5% of younger individuals who did experience side effects
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(1)

  # The 5% of older individuals who did not experience side effects
  random_older = randint(65,100)
  train_samples.append(random_older)
  train_labels.append(0)

for i in range(1000):
  # The 95% of younger individuals who did not experience side effects
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(0)

  # The 95% of older individuals who did experience side effects
  random_older = randint(65,100)
  train_samples.append(random_older)
  train_labels.append(1)

In [5]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels,train_samples = shuffle(train_labels,train_samples)

In [6]:
train_labels

array([0, 0, 0, ..., 1, 0, 0])

In [7]:
train_samples

array([58, 20, 56, ..., 26, 59, 49])

In [8]:
train_labels,train_samples

(array([0, 0, 0, ..., 1, 0, 0]), array([58, 20, 56, ..., 26, 59, 49]))

In [9]:
shuffle(train_labels,train_samples)

[array([1, 0, 0, ..., 0, 1, 0]), array([81, 62, 26, ..., 36, 84, 58])]

In [10]:
scaler = MinMaxScaler(feature_range = (0,1))
sc_trained_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [ ]:
for i in sc_trained_samples:
  print(i)

In [13]:
sc_trained_samples = np.array(sc_trained_samples)
sc_trained_samples

array([[0.51724138],
       [0.08045977],
       [0.49425287],
       ...,
       [0.14942529],
       [0.52873563],
       [0.4137931 ]])

In [14]:
!pip install keras 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [17]:
import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense
from keras.optimizers import adam_v2
#from tensorflow.keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras import optimizers
from keras import metrics

In [18]:
model = Sequential([
                    Dense(units = 20,input_shape = (1,),activation = 'relu'),
                    Dense(units = 10,activation = 'relu'),
                    Dense(units = 2,activation = 'softmax')
])

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 20)                40        
                                                                 
 dense_1 (Dense)             (None, 10)                210       
                                                                 
 dense_2 (Dense)             (None, 2)                 22        
                                                                 
Total params: 272
Trainable params: 272
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.loss = 'sparse_categorical_crossentropy'

In [21]:
#model.compile(optimizer=adam_v2, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam')

In [22]:
model.fit(sc_trained_samples, train_labels, batch_size=10, epochs=200, shuffle=True, verbose=2)

Epoch 1/200
210/210 - 1s - loss: 0.5727 - 837ms/epoch - 4ms/step
Epoch 2/200
210/210 - 0s - loss: 0.4066 - 280ms/epoch - 1ms/step
Epoch 3/200
210/210 - 0s - loss: 0.3009 - 262ms/epoch - 1ms/step
Epoch 4/200
210/210 - 0s - loss: 0.2625 - 273ms/epoch - 1ms/step
Epoch 5/200
210/210 - 0s - loss: 0.2515 - 241ms/epoch - 1ms/step
Epoch 6/200
210/210 - 0s - loss: 0.2448 - 259ms/epoch - 1ms/step
Epoch 7/200
210/210 - 0s - loss: 0.2429 - 251ms/epoch - 1ms/step
Epoch 8/200
210/210 - 0s - loss: 0.2395 - 246ms/epoch - 1ms/step
Epoch 9/200
210/210 - 0s - loss: 0.2370 - 249ms/epoch - 1ms/step
Epoch 10/200
210/210 - 0s - loss: 0.2359 - 247ms/epoch - 1ms/step
Epoch 11/200
210/210 - 0s - loss: 0.2337 - 252ms/epoch - 1ms/step
Epoch 12/200
210/210 - 0s - loss: 0.2332 - 243ms/epoch - 1ms/step
Epoch 13/200
210/210 - 0s - loss: 0.2318 - 259ms/epoch - 1ms/step
Epoch 14/200
210/210 - 0s - loss: 0.2303 - 247ms/epoch - 1ms/step
Epoch 15/200
210/210 - 0s - loss: 0.2309 - 246ms/epoch - 1ms/step
Epoch 16/200
210/21

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential([
    Dense(32, input_shape=(10,), activation='relu'),
    Dense(2, activation='softmax'),
])


In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential([
    Dense(5, input_shape=(3,), activation='relu'),
    Dense(2, activation='softmax'),
])