In [ ]:
import numpy as np

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
from keras.datasets import mnist 
(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
#train data
print(train_images.shape)
print(train_labels.shape)
train_labels

(60000, 28, 28)
(60000,)


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
#test data
print(test_images.shape)
print(test_labels.shape)
test_labels

(10000, 28, 28)
(10000,)


array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [ ]:
my_slice = train_images[10:100]
print(my_slice.shape)

(90, 28, 28)


In [ ]:
my_slice = train_images[10]
print(my_slice.shape)

(28, 28)


In [ ]:
my_slice = train_images[:, 14:, 14:]
print(my_slice)

[[[240 253 253 ...   0   0   0]
  [ 45 186 253 ...   0   0   0]
  [  0  16  93 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[241 243 234 ...   0   0   0]
  [143  91  28 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 ...

 [[253 254 253 ...   0   0   0]
  [ 72 192 254 ...   0   0   0]
  [  0   6 242 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0  31 127 ...   0   0   0]
  [ 27 218 252 ...   0   0   0]
  [194 253 217 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0  

In [ ]:
my_slice = train_images[:, 7:-7, 7:-7]
print(my_slice)

In [ ]:
batch = train_images[:128]
batch

In [ ]:
batch1 = train_images[128:256]
batch1

batchn = train_images[128 * n:128 * (n + 1)]

In [ ]:
import numpy as np
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)

In [ ]:
z = np.dot(x, y)

ValueError: ignored

Tensor Reshaping

In [ ]:
x = np.array([[0., 1.],
[2., 3.],
[4., 5.]])
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
print(x.shape)

(3, 2)


In [ ]:
x = x.reshape((6, 1))
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [ ]:
x = x.reshape((2, 3))
x

array([[0., 1., 2.],
       [3., 4., 5.]])

In [ ]:
o = np.zeros((300, 20)) #Creates an all-zeros matrix of shape (300, 20)
o = np.transpose(o)
print(type(o))
print(o.shape)

<class 'numpy.ndarray'>
(20, 300)
